apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: welcome-php
  name: welcome-php
  namespace: kapp
spec:
  type: LoadBalancer
  selector:
    app: welcome-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080